# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/shubhamahlawat/Course Work/oopsProject/dashboard.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(806, 638)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(-40, -21, 881, 791))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.983, stop:0 rgba(86, 153, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.bgwidget.setObjectName("bgwidget")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(360, 560, 161, 20))
        self.error.setStyleSheet("color:rgb(255, 0, 0)")
        self.error.setText("")
        self.error.setObjectName("error")
        self.ATwidget = QtWidgets.QWidget(self.bgwidget)
        self.ATwidget.setGeometry(QtCore.QRect(50, 90, 781, 161))
        self.ATwidget.setStyleSheet("QWidget#ATwidget{\n"
"background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white;\n"
"}")
        self.ATwidget.setObjectName("ATwidget")
        self.label = QtWidgets.QLabel(self.ATwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 81, 21))
        self.label.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.ATwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 40, 31, 16))
        self.label_2.setObjectName("label_2")
        self.task_name = QtWidgets.QLineEdit(self.ATwidget)
        self.task_name.setGeometry(QtCore.QRect(90, 40, 191, 21))
        self.task_name.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white;")
        self.task_name.setObjectName("task_name")
        self.label_3 = QtWidgets.QLabel(self.ATwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 70, 91, 16))
        self.label_3.setObjectName("label_3")
        self.task_description = QtWidgets.QTextEdit(self.ATwidget)
        self.task_description.setGeometry(QtCore.QRect(90, 70, 681, 41))
        self.task_description.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white;")
        self.task_description.setObjectName("task_description")
        self.addTaskBtn = QtWidgets.QPushButton(self.ATwidget)
        self.addTaskBtn.setGeometry(QtCore.QRect(590, 120, 171, 31))
        self.addTaskBtn.setStyleSheet("")
        self.addTaskBtn.setObjectName("addTaskBtn")
        self.label_4 = QtWidgets.QLabel(self.ATwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setObjectName("label_4")
        self.checkBox = QtWidgets.QCheckBox(self.ATwidget)
        self.checkBox.setGeometry(QtCore.QRect(100, 120, 86, 20))
        self.checkBox.setText("")
        self.checkBox.setObjectName("checkBox")
        self.welcome = QtWidgets.QLabel(self.bgwidget)
        self.welcome.setGeometry(QtCore.QRect(330, 30, 411, 41))
        self.welcome.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.welcome.setStyleSheet("font: 18pt \".AppleSystemUIFont\";")
        self.welcome.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.welcome.setObjectName("welcome")
        self.tableWidget = QtWidgets.QTableWidget(self.bgwidget)
        self.tableWidget.setGeometry(QtCore.QRect(50, 260, 781, 211))
        self.tableWidget.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white;")
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(3)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        self.label_5 = QtWidgets.QLabel(self.bgwidget)
        self.label_5.setGeometry(QtCore.QRect(750, 30, 51, 51))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("/Users/shubhamahlawat/Course Work/oopsProject/user.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.plotbtn = QtWidgets.QPushButton(self.bgwidget)
        self.plotbtn.setGeometry(QtCore.QRect(340, 490, 191, 31))
        self.plotbtn.setObjectName("plotbtn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Add Task"))
        self.label_2.setText(_translate("Dialog", "Title"))
        self.label_3.setText(_translate("Dialog", "Description"))
        self.addTaskBtn.setText(_translate("Dialog", "Add Task"))
        self.label_4.setText(_translate("Dialog", "Productive ?"))
        self.welcome.setText(_translate("Dialog", "Welcome Human"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Time"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Title"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Description"))
        self.plotbtn.setText(_translate("Dialog", "Plot your Productivity"))
