# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/shubhamahlawat/Course Work/oopsProject/LoginScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(801, 632)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 811, 631))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.983, stop:0 rgba(86, 153, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(330, 60, 111, 51))
        self.label.setStyleSheet("color : white ;\n"
"font: 40pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 140, 361, 61))
        self.label_2.setStyleSheet("color: white;\n"
"font: 30px;")
        self.label_2.setObjectName("label_2")
        self.loginButton = QtWidgets.QPushButton(self.bgwidget)
        self.loginButton.setGeometry(QtCore.QRect(270, 470, 271, 50))
        self.loginButton.setStyleSheet("background-color:rgb(55, 112, 255);\n"
"color:rgb(255, 255, 255);\n"
"font: 25pt \"Ubuntu\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"")
        self.loginButton.setObjectName("loginButton")
        self.emailFeild = QtWidgets.QLineEdit(self.bgwidget)
        self.emailFeild.setEnabled(True)
        self.emailFeild.setGeometry(QtCore.QRect(270, 270, 271, 51))
        self.emailFeild.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white")
        self.emailFeild.setObjectName("emailFeild")
        self.passwordFeild = QtWidgets.QLineEdit(self.bgwidget)
        self.passwordFeild.setGeometry(QtCore.QRect(270, 380, 271, 51))
        self.passwordFeild.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white")
        self.passwordFeild.setObjectName("passwordFeild")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(270, 210, 271, 61))
        self.label_3.setStyleSheet("color: white;\n"
"font: 30px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(270, 320, 271, 61))
        self.label_4.setStyleSheet("color: white;\n"
"font: 30px;")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(270, 440, 161, 20))
        self.error.setStyleSheet("color:rgb(255, 0, 0)")
        self.error.setText("")
        self.error.setObjectName("error")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Log-In"))
        self.label_2.setText(_translate("Dialog", "Sign in to your account"))
        self.loginButton.setText(_translate("Dialog", "Log-In"))
        self.label_3.setText(_translate("Dialog", "E-mail"))
        self.label_4.setText(_translate("Dialog", "Password"))
