# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/shubhamahlawat/Course Work/oopsProject/SignUp.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(806, 638)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 881, 640))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.983, stop:0 rgba(86, 153, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(330, 60, 161, 51))
        self.label.setStyleSheet("color : white ;\n"
"font: 40pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(260, 120, 361, 61))
        self.label_2.setStyleSheet("color: white;\n"
"font: 30px;")
        self.label_2.setObjectName("label_2")
        self.signUpButton = QtWidgets.QPushButton(self.bgwidget)
        self.signUpButton.setEnabled(True)
        self.signUpButton.setGeometry(QtCore.QRect(270, 480, 271, 50))
        self.signUpButton.setStyleSheet("background-color:rgb(55, 112, 255);\n"
"color:rgb(255, 255, 255);\n"
"font: 25pt \"Ubuntu\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"")
        self.signUpButton.setObjectName("signUpButton")
        self.emailFeild = QtWidgets.QLineEdit(self.bgwidget)
        self.emailFeild.setEnabled(True)
        self.emailFeild.setGeometry(QtCore.QRect(280, 290, 241, 31))
        self.emailFeild.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white")
        self.emailFeild.setObjectName("emailFeild")
        self.passwordFeild = QtWidgets.QLineEdit(self.bgwidget)
        self.passwordFeild.setGeometry(QtCore.QRect(280, 360, 241, 31))
        self.passwordFeild.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white")
        self.passwordFeild.setObjectName("passwordFeild")
        self.label_3 = QtWidgets.QLabel(self.bgwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 270, 261, 16))
        self.label_3.setStyleSheet("color: white;\n"
"font: 20px;")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.bgwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 330, 271, 31))
        self.label_4.setStyleSheet("color: white;\n"
"font: 20px;")
        self.label_4.setObjectName("label_4")
        self.error = QtWidgets.QLabel(self.bgwidget)
        self.error.setGeometry(QtCore.QRect(360, 560, 161, 20))
        self.error.setStyleSheet("color:rgb(255, 0, 0)")
        self.error.setText("")
        self.error.setObjectName("error")
        self.cnf_passwordFeild = QtWidgets.QLineEdit(self.bgwidget)
        self.cnf_passwordFeild.setGeometry(QtCore.QRect(280, 430, 241, 31))
        self.cnf_passwordFeild.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white")
        self.cnf_passwordFeild.setObjectName("cnf_passwordFeild")
        self.label_9 = QtWidgets.QLabel(self.bgwidget)
        self.label_9.setGeometry(QtCore.QRect(280, 410, 271, 16))
        self.label_9.setStyleSheet("color: white;\n"
"font: 20px;")
        self.label_9.setObjectName("label_9")
        self.nameFeild = QtWidgets.QLineEdit(self.bgwidget)
        self.nameFeild.setEnabled(True)
        self.nameFeild.setGeometry(QtCore.QRect(280, 220, 241, 31))
        self.nameFeild.setStyleSheet("background-color: rgba(0,0,0,0);\n"
"border-style:outset;\n"
"border-width: 1px;\n"
"border-color:white")
        self.nameFeild.setObjectName("nameFeild")
        self.label_10 = QtWidgets.QLabel(self.bgwidget)
        self.label_10.setGeometry(QtCore.QRect(280, 200, 261, 16))
        self.label_10.setStyleSheet("color: white;\n"
"font: 20px;")
        self.label_10.setObjectName("label_10")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Sign - Up"))
        self.label_2.setText(_translate("Dialog", "Sign Up for your account"))
        self.signUpButton.setText(_translate("Dialog", "Sign - Up"))
        self.label_3.setText(_translate("Dialog", "E-mail"))
        self.label_4.setText(_translate("Dialog", "Password"))
        self.label_9.setText(_translate("Dialog", "Re-Enter Password"))
        self.label_10.setText(_translate("Dialog", "Name"))
