# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/shubhamahlawat/Course Work/oopsProject/SignInWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(811, 631)
        Dialog.setSizeGripEnabled(False)
        self.bgwidget = QtWidgets.QWidget(Dialog)
        self.bgwidget.setEnabled(True)
        self.bgwidget.setGeometry(QtCore.QRect(0, 0, 811, 631))
        self.bgwidget.setStyleSheet("QWidget#bgwidget{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0.983, stop:0 rgba(86, 153, 255, 255), stop:1 rgba(255, 255, 255, 255))\n"
"}")
        self.bgwidget.setObjectName("bgwidget")
        self.label = QtWidgets.QLabel(self.bgwidget)
        self.label.setGeometry(QtCore.QRect(340, 80, 181, 41))
        self.label.setStyleSheet("color : white ;\n"
"font: 40pt \"Ubuntu\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.bgwidget)
        self.label_2.setGeometry(QtCore.QRect(240, 140, 361, 61))
        self.label_2.setStyleSheet("color: white;\n"
"font: 30px;")
        self.label_2.setObjectName("label_2")
        self.login = QtWidgets.QPushButton(self.bgwidget)
        self.login.setGeometry(QtCore.QRect(290, 250, 271, 51))
        self.login.setStyleSheet("background-color:rgb(55, 112, 255);\n"
"color:rgb(255, 255, 255);\n"
"font: 25pt \"Ubuntu\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"")
        self.login.setObjectName("login")
        self.signUp = QtWidgets.QPushButton(self.bgwidget)
        self.signUp.setGeometry(QtCore.QRect(290, 320, 271, 51))
        self.signUp.setStyleSheet("background-color:rgb(55, 112, 255);\n"
"color:rgb(255, 255, 255);\n"
"font: 25pt \"Ubuntu\";\n"
"border-style: outset;\n"
"border-width: 2px;\n"
"border-radius: 20px;\n"
"border-color: white;\n"
"")
        self.signUp.setObjectName("signUp")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Welcome"))
        self.label_2.setText(_translate("Dialog", "Sign in or Create an account"))
        self.login.setText(_translate("Dialog", "Log In"))
        self.signUp.setText(_translate("Dialog", "Sign Up"))
